### PR TITLE
fix: Improve "/whitelist" syntax and use dynamic memory

### PR DESCRIPTION
**Pull request by GitMensch**
fixing a reference-out-of-bounds exception in case of "list" command and lots of whitelisted users (max: 100 users * 16 chars = 1600 with buffer being of size 255)

showcasing:
* `STRING ... WITH POINTER` (that would also never write out of bounds and would allow an easy `ON OVERFLOW EXIT PERFORM`)
* `EVALUATE` statement, including `ALSO`
* mixed static and "if needed" dynamic memory

Warning: the initial reason was showcasing this use of `EVALUATE`, followed by recognition of better using `STRING WITH POINTER`, then realizing a not unlikely exception (first fixed by that `ON OVERFLOW`), then thinking about showcasing dynamic memory...

This PR is: totally untested (just checked that it compiles with GC 3.1, which needed some adjustments how `ALLOCATE`+`FREE` are used) and GC 3.2 and additional needs #294 to be merged up-front (if not wanted a `MOVE SPACES TO DYN-BUFFER (BUFFER-POS:)` instead of that `SUBTRACT` to get the length would be possible).

As noted this was mostly about showcasing those more rare used COBOL language features, feel free to pick only parts and/or adjust if others fall in the "less clear" or even "unmaintainable" state. The thing that likely should get in is the `STRING` (with `ON OVERFLOW` if the dynamic memory part is not used.

### CODE REVIEW

**Comment by meyfa** [comment]
The changes make sense to me, however there is a compilation error:

```
src/commands/whitelist.cob:102: error: 'BUFFER-ADDRESS' is not defined
  100 |                 *> overwrite the dynamic buffer's address with a dynamic..
  101 |                 IF DYN-BUFFER-LEN > LENGTH OF BUFFER
  102 >                    ALLOCATE DYN-BUFFER-LEN CHARACTERS RETURNING BUFFER-AD..
  103 |                    SET ADDRESS OF DYN-BUFFER TO BUFFER-ADDRESS
  104 |                 ELSE
```

Could you please take a look?

Also, it may seem wrong, but the message format "There are [n] whitelisted player(s)" was actually intentional. This is the exact message that the official Minecraft server sends (yes, even for n=1). Hence, this should be reverted.

**Comment by GitMensch** [comment]
fixed the missing variable, restored the strange but default "1 player(s): " message

**Comment by meyfa** [comment]
Hey @GitMensch, thanks for the contribution.

I've taken the liberty of reformatting the code a bit, and added #294 back in (this time with `OPTIONAL`). Tests look good with N=0, N=1, and N>1.
